source 'https://rubygems.org'

gem "rake"
gem "minitest"
gem "redis"
gem "pg"
gem "mysql2"
gem "dalli"
gem "elasticsearch"
gem "curb"
gem "http"
gem "rest-client"
gem "activerecord", require: "active_record"
gem "typhoeus"
gem "searchkick"
gem "mongo"
gem "faraday"
gem "bunny"
gem "twilio-ruby"
gem "geocoder"
gem "koala"
gem "httparty"
gem "hipchat"
gem "httpclient"
gem "firebase"
gem "stripe", github: "stripe/stripe-ruby"
gem "sequel"
gem "connection_pool"
