source 'https://rubygems.org'

gem "rake"
gem "minitest"
gem "redis"
gem "pg"
gem "mysql2"
gem "dalli"
gem "elasticsearch"
gem "curb"
gem "http"
gem "rest-client"
gem "activerecord", require: "active_record"
gem "typhoeus"
gem "searchkick"
gem "mongo"
gem "faraday"
gem "bunny"
gem "twilio-ruby"
gem "geocoder"
gem "koala"
gem "httparty"
gem "hipchat"
gem "httpclient"
gem "firebase"
gem "stripe", ">= 1.24.0"
gem "sequel"
gem "connection_pool"
gem "mongoid"
gem "httpi"
gem "em-http-request"
gem "patron"
gem "excon"
gem "mechanize"
gem "gibbon"
gem "bitly"
gem "actionmailer"
gem "slack-notifier"
gem "net-dns"
gem "net-ssh"
gem "twitter"
gem "rsolr"
gem "ruby-kafka"
gem "mail", ">= 2.7.0"
gem "aws-sdk-s3"
#gem "kubeclient", git: "https://github.com/abonas/kubeclient.git"
gem "activemerchant"
gem "google-cloud"
